import type { INodeProperties } from 'n8n-workflow';

export const supportDescription: INodeProperties[] = [
                {
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					]
				}
			},
			"options": [
				{
					"name": "Get Tickets",
					"value": "Get Tickets",
					"action": "Support Tickets List",
					"description": "Returns a collection of Support Tickets on your Account. Support Tickets can be both tickets you open with Linode for support, as well as tickets generated by Linode regarding your Account.\nThis collection includes all Support Tickets generated on your Account, with open tickets returned first.\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/support/tickets"
						}
					}
				},
				{
					"name": "Create Ticket",
					"value": "Create Ticket",
					"action": "Support Ticket Open",
					"description": "Open a Support Ticket.\nOnly one of the ID attributes (`linode_id`, `domain_id`, etc.) can be set on a single Support Ticket.\n",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/support/tickets"
						}
					}
				},
				{
					"name": "Get Ticket",
					"value": "Get Ticket",
					"action": "Support Ticket View",
					"description": "Returns a Support Ticket under your Account.\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/support/tickets/{{$parameter[\"ticketId\"]}}"
						}
					}
				},
				{
					"name": "Create Ticket Attachment",
					"value": "Create Ticket Attachment",
					"action": "Support Ticket Attachment Create",
					"description": "Adds a file attachment to an existing Support\nTicket on your Account. File attachments are used to assist our\nSupport team in resolving your Ticket. Examples of attachments\nare screen shots and text files that provide additional information.\n\nThe file attachment is submitted in the request as multipart/form-data.\n\n**Note**: Accepted file extensions include: .gif, .jpg, .jpeg, .pjpg,\n.pjpeg, .tif, .tiff, .png, .pdf, or .txt.\n",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/support/tickets/{{$parameter[\"ticketId\"]}}/attachments"
						}
					}
				},
				{
					"name": "Close Ticket",
					"value": "Close Ticket",
					"action": "Support Ticket Close",
					"description": "Closes a Support Ticket you have access to modify.\n",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/support/tickets/{{$parameter[\"ticketId\"]}}/close"
						}
					}
				},
				{
					"name": "Get Ticket Replies",
					"value": "Get Ticket Replies",
					"action": "Replies List",
					"description": "Returns a collection of replies to a Support Ticket on your Account.\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/support/tickets/{{$parameter[\"ticketId\"]}}/replies"
						}
					}
				},
				{
					"name": "Create Ticket Reply",
					"value": "Create Ticket Reply",
					"action": "Reply Create",
					"description": "Adds a reply to an existing Support Ticket.\n",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/support/tickets/{{$parameter[\"ticketId\"]}}/replies"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /support/tickets",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Tickets"
					]
				}
			}
		},
		{
			"displayName": "Page",
			"name": "page",
			"description": "The page of a collection to return.",
			"default": 1,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "page",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Tickets"
					]
				}
			}
		},
		{
			"displayName": "Page Size",
			"name": "page_size",
			"description": "The number of items to return per page.",
			"default": 100,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "page_size",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Tickets"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Tickets"
					]
				}
			}
		},
		{
			"displayName": "POST /support/tickets",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Database ID",
			"name": "database_id",
			"type": "number",
			"default": 0,
			"description": "The ID of the Managed Database this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "database_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Description",
			"name": "description",
			"type": "string",
			"default": "I'm having trouble setting the root password on my Linode. I tried following the instructions but something is not working and I'm not sure what I'm doing wrong. Can you please help me figure out how I can reset it?\n",
			"description": "The full details of the issue or question.\n",
			"routing": {
				"send": {
					"property": "description",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Domain ID",
			"name": "domain_id",
			"type": "number",
			"default": null,
			"description": "The ID of the Domain this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "domain_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Firewall ID",
			"name": "firewall_id",
			"type": "number",
			"default": 0,
			"description": "The ID of the Firewall this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "firewall_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Linode ID",
			"name": "linode_id",
			"type": "number",
			"default": 123,
			"description": "The ID of the Linode this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "linode_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Lkecluster ID",
			"name": "lkecluster_id",
			"type": "number",
			"default": 123,
			"description": "The ID of the Kubernetes cluster this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "lkecluster_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Longviewclient ID",
			"name": "longviewclient_id",
			"type": "number",
			"default": null,
			"description": "The ID of the Longview client this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "longviewclient_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Managed Issue",
			"name": "managed_issue",
			"type": "boolean",
			"default": false,
			"description": "Designates if this ticket is related to a [Managed service](https://www.linode.com/products/managed/). If `true`, the following constraints will apply:\n* No ID attributes (i.e. `linode_id`, `domain_id`, etc.) should be provided with this request.\n* Your account must have a [Managed service enabled](/docs/api/managed/#managed-service-enable).\n",
			"routing": {
				"send": {
					"property": "managed_issue",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Nodebalancer ID",
			"name": "nodebalancer_id",
			"type": "number",
			"default": null,
			"description": "The ID of the NodeBalancer this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "nodebalancer_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Region",
			"name": "region",
			"type": "string",
			"default": null,
			"description": "The [Region](/docs/api/regions/) ID for the associated VLAN this ticket is regarding.\n\nOnly allowed when submitting a VLAN ticket.\n",
			"routing": {
				"send": {
					"property": "region",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Summary",
			"name": "summary",
			"type": "string",
			"default": "Having trouble resetting root password on my Linode\n",
			"description": "The summary or title for this SupportTicket.\n",
			"routing": {
				"send": {
					"property": "summary",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Vlan",
			"name": "vlan",
			"type": "string",
			"default": null,
			"description": "The label of the VLAN this ticket is regarding, if relevant. To view your VLANs, use the VLANs List ([GET /networking/vlans](/docs/api/networking/#vlans-list)) endpoint.\n\nRequires a specified `region` to identify the VLAN.\n",
			"routing": {
				"send": {
					"property": "vlan",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Volume ID",
			"name": "volume_id",
			"type": "number",
			"default": null,
			"description": "The ID of the Volume this ticket is regarding, if relevant.\n",
			"routing": {
				"send": {
					"property": "volume_id",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket"
					]
				}
			}
		},
		{
			"displayName": "GET /support/tickets/{ticketId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket"
					]
				}
			}
		},
		{
			"displayName": "POST /support/tickets/{ticketId}/attachments",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Attachment"
					]
				}
			}
		},
		{
			"displayName": "POST /support/tickets/{ticketId}/attachments<br/><br/>There's no body available for request, kindly use HTTP Request node to send body",
			"name": "operation",
			"type": "notice",
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Attachment"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Attachment"
					]
				}
			}
		},
		{
			"displayName": "POST /support/tickets/{ticketId}/close",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Close Ticket"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Close Ticket"
					]
				}
			}
		},
		{
			"displayName": "GET /support/tickets/{ticketId}/replies",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket Replies"
					]
				}
			}
		},
		{
			"displayName": "Page",
			"name": "page",
			"description": "The page of a collection to return.",
			"default": 1,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "page",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket Replies"
					]
				}
			}
		},
		{
			"displayName": "Page Size",
			"name": "page_size",
			"description": "The number of items to return per page.",
			"default": 100,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "page_size",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket Replies"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Get Ticket Replies"
					]
				}
			}
		},
		{
			"displayName": "POST /support/tickets/{ticketId}/replies",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Reply"
					]
				}
			}
		},
		{
			"required": true,
			"displayName": "Description",
			"name": "description",
			"type": "string",
			"default": "Thank you for your help. I was able to figure out what the problem was and I successfully reset my password. You guys are the best!\n",
			"description": "The content of your reply.\n",
			"routing": {
				"send": {
					"property": "description",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Reply"
					]
				}
			}
		},
		{
			"displayName": "Bearer Token",
			"name": "security_personalaccesstoken",
			"type": "string",
			"default": "",
			"description": "HTTP bearer authentication for personalAccessToken",
			"required": false,
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ 'Bearer ' + $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Support"
					],
					"operation": [
						"Create Ticket Reply"
					]
				}
			}
		},
];
